name: Build & Deploy to Server

on:
  push:
    branches: [staging]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create .env file from secret
        run: |
          echo "${{ secrets.ENV_FE_STAGING }}" > .env

      - name: Build Docker image
        run: |
          docker build -t kubik-frontend:latest .

      - name: Save image
        run: docker save kubik-frontend:latest | gzip > kubik-frontend.tar.gz

      - name: Copy image to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: 'kubik-frontend.tar.gz'
          target: '/root/'

      - name: Deploy on server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker ps -q --filter "publish=8090" | xargs -r docker stop
            gunzip -c kubik-frontend.tar.gz | docker load
            docker rm kubik-frontend || true
            docker run -d --name kubik-frontend --restart always -p 8090:8090 kubik-frontend:latest
