name: Deploy POS FE

on:
  push:
    tags:
      - 'v*.*.*'

env:
  APP_NAME: pos-frontend
  STACK_NAME: pos
  REGISTRY: ghcr.io

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set variables
        run: |
          REPO_OWNER=$(echo "${GITHUB_REPOSITORY_OWNER}" | tr '[:upper:]' '[:lower:]')
          RAW_VERSION=${GITHUB_REF#refs/tags/}
          VERSION=$(echo "$RAW_VERSION" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9._-]//g')
          IMAGE=$REGISTRY/$REPO_OWNER/pos-frontend

          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Create .env file
        run: |
          # belum ada yang literally rahasia, jadi aman untuk di hardcode
          cat << EOF > .env
          VITE_APP_MODE=production
          VITE_APP_BASE_API_PREFIX=/api
          VITE_APP_BASE_API_URL=https://api.kubikpos.id
          VITE_APP_BASE_BUCKET_URL=https://wkgt-asset.online/
          VITE_APP_BASE_URL=https://pos.kubikpos.id
          VITE_APP_BASE_URL_RENEW_SUBSCRIPTION=https://kubikpos.id/dashboard
          EOF

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build & push Docker image
        run: |
          docker build -t $IMAGE:$VERSION -t $IMAGE:latest .
          docker push $IMAGE:$VERSION
          docker push $IMAGE:latest

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.PROD_IP }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_KEY }}
          script: |
            IMAGE=ghcr.io/kubik-erp/pos-frontend:latest
            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USER }} --password-stdin
            docker pull $IMAGE
            docker stack deploy -c /root/deploy/pos-fe-stack.yml pos --with-registry-auth
            docker service update --force pos_pos-frontend
